[package]
name = "example"
version = "0.1.0"
authors = ["Freddy L P.B <freddy_luis_94@hotmail.com>"]
edition = "2018"

[dependencies]
clapi = { path="../clapi", features=["macros", "serde"] }
serde = { version="1.0.118", features=["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
