[package]
name = "example"
version = "0.1.0"
authors = ["Freddy L P.B <freddy_luis_94@hotmail.com>"]
edition = "2018"

[dependencies]
clapi = { path="../clapi", features=["macros"] }
serde = { version="1.0.118", features=["derive"] }