[workspace]
members=[
    "clapi",
    "clapi_macros",
    "clapi_internal",

    # Internal
    "test_suite",
    "benches",
    "examples/*"
]

exclude=[
    "examples/*",
    "benches",
    "test_suite",
]