[package]
name = "benches"
version = "0.0.0"
authors = ["Freddy L"]
edition = "2021"
publish = false

[dependencies]
clapi = { path="../clapi" }
bencher = "0.1.5"

[[bench]]
name = "0_command"
path = "0_command.rs"
harness = false

[[bench]]
name = "1_help"
path = "1_help.rs"
harness = false