[package]
name = "clapi_macros"
version = "0.1.0"
authors = ["Freddy L P.B <freddy_luis_94@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
macro_attribute = { path = "macro_attribute" }
clapi = { path="../clapi" }
proc-macro2 = "1.0.24"
syn = {version="1.0.45", features=["full", "extra-traits", "parsing"]}
quote = "1.0.7"

#[dev-dependencies]
#macro_tests = { path = "./macro_tests" }